# Page settings
baseurl = "www.apibot.co"
title = "Elate theme"
languageCode = "en-us"
theme = "hugo-elate-theme"
googleAnalytics = "UA-100119885-1"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Carlos Duque"
  description = ""
  email = "carlosduque@apibot.co"
  # Navigation
  [params.navigation]
    brand = "Apibot"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"
    docs = "Docs"
    faq = "faq"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Do API integration test in minutes!"
    subtitle = 'If you do not want to miss out on being part of the next integration tool revolution, please <a href="#fh5co-contact" title="Contact us">reach us</a> and be part of our beta users'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Flow of Information"
    description = "Keeps flow of information or sequence of steps chain together                                                                                                                                      "
    url = "/docs/concepts/execution/"
    button = "Get In Touch"
    icon = "icon-share"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "GUI"
    description = "With our GUI testing should be something easy and efficient, developing a test scenario in minutes                                                                                                 "
    url = "/docs/concepts/execution/"
    button = "Click Me"
    icon = "icon-clock"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Multiple Data Entry"
    description = "Do you need to run your script multiple times with N different Data? Apibot with it easy to use data import, let you do that in seconds"
    url = "#"
    button = "Why us?"
    icon = "icon-table"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Apibot Making an HTTP Request"
    icon = "icon-play2"
    url = "https://player.vimeo.com/video/225732161"


  # Work section
  [params.work]
    enable = true
    title = "Powerful"
    description = "With Apibot there are things that no current tool can do, and there is more coming."
    footertext = '** These are examples of what you could do with apibot consult our <a href="/docs/" target="_blank">documentation</a>'

    [[params.work.row]]
      img = "fork-join.png"
      alt = "Fork and Join Graph"
      title = "Flexible"
      subtitle = "Simple and flexible execution"

    [[params.work.row]]
      img = "graph-reuse.png"
      alt = "Image2"
      title = "Reuse"
      subtitle = "Reuse your graphs. You will become super fast!"

    [[params.work.row]]
      img = "logic-script.png"
      alt = "Image3"
      title = "Logic"
      subtitle = "Apply logic to your scenarios. Having more power over your tests"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Hear stories from around the world"

    [[params.testimonials.item]]
      quote = "&ldquo; I love the program, what I see to be the most useful is the fact that I could visualize interactions with an API. I have been working with a lot of APIs that I did not write, and I have been struggling with understanding the flow of information.&rdquo;"
      person = 'Andres Bernal, <span class="subtext">CEO,</span> <a href="https://www.loenvio.co" target="_blank">loEnvio</a>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;I like that I can run multiple scenarios in no time. After our team was able to learn the tool, it has allowed us to save a lot of time and effort on testing or APIs. It is the best tool on the market by far!&rdquo;"
      person = 'Cristian Pinilla, <span class="subtext">Project Manager,</span> <a href="http://myass.co" target="_blank">ASS</a>'
      img = "person2.jpg"
      alt = "Person2"
    



  # Services section
  # Cross platform: available on windows, linux and OSX
  # Managed execution: design your tests locally, run them periodically on our cloud.
  # Monitoring: Email alerts and integrations alert you when your tests fail.
  # Javascript Support: Apibot is easily customizable with Javascript.
  [params.services]
    enable = true
    title = "Services"
    description = "Take advantage of our powerfull tool, this is only a minor idea of what we provide"

    [[params.services.item]]
      title = "Managed execution"
      description = "design your tests locally, run them periodically on our cloud"
      icon = "icon-cloud-upload"

    [[params.services.item]]
      title = "Cross platform &amp; Beautiful Interface"
      description = "available on windows, linux and OSX"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Reports &amp; Monitoring"
      description = "Email alerts and integrations alert you when your tests fail"
      icon = "icon-video2"

      [[params.services.item]]
      title = "Javascript &amp; Clojure"
      description = "Apibot is easily customizable with Javascript or Clojure"      
      icon = "icon-speech"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "We are a two person team"

    [[params.about.item]]
      name = "Fernando Hurtado"
      position = "The mind behind the App"
      description = "The Hacker with 4 years of experience, writing high-quality software. Appasionate for automation and his disappointment with the current API automation tooling environment led him to start Apibot"
      img = "fernando-hurtado.jpg"
      alt = "Fernando Hurtado"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Carlos Duque"
      position = "The marketing Guru!"
      description = "Our sales and marketing guru. 4 years of experience working as a consultant, makes him the ideal guy to create lasting relationships with our customers. Don't hesitate to reach unto him; he might as well invite you for a beer. "
      img = "carlos-duque.jpg"
      alt = "Person2"
      social = [
        ["icon-linkedin", "https://twitter.com/ceduquey"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]     

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 16
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 8470
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 7
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "Reach out if you have any question or if you just want to say hello :)"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Johan Huizingalaan 763A, 1066 VH <br> Amsterdam, Netherlands"],
        ["icon-phone", "+31 (650) 413-182"],
        ["icon-social-skype", "ceduquey"],
        ["icon-envelope", "carlosduque@apibot.co"],
        ["icon-globe", '<a href="http://apibot.co/" target="_blank">apibot.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone or Skype account"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Apibot. All Rights Reserved. <br> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a>'


  # Docs section
  [params.docs]
    enable = true
    title = "Docs"
    description = "Documentation on Apibot"

  # FAQ section
  [params.faq]
    enable = false
    title = "FAQ"
    description = "Frequently Asked Questions"
